name: Convert HaGeZi Rule-sets

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3 AM UTC

jobs:
  create_tag:
    name: Create Release Tag
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag.outputs.new_tag }}  # Pass tag name to other jobs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create and Push New Tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: false  # No auto version bump
          WITH_V: false
          CUSTOM_TAG: daily-$(date +'%Y%m%d')

  build:
    name: Convert and Upload Rule-sets
    needs: create_tag
    runs-on: ubuntu-latest

    strategy:
      matrix:
        list: 
          - normal
          - pro
        include:
          - list: normal
            filename: "multi.txt"
          - list: pro
            filename: "pro.txt"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up SagerNet APT Repository
        run: |
          sudo mkdir -p /etc/apt/keyrings
          sudo curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc
          sudo chmod a+r /etc/apt/keyrings/sagernet.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/sagernet.asc] https://deb.sagernet.org/ * *" | sudo tee /etc/apt/sources.list.d/sagernet.list > /dev/null
          sudo apt-get update

      - name: Install sing-box
        run: |
          sudo apt-get install -y sing-box
          sing-box version

      - name: Download HaGeZi List - ${{ matrix.list }}
        run: |
          wget -O hagezi-${{ matrix.list }}.txt "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/${{ matrix.filename }}"

      - name: Convert List to Binary Rule-set - ${{ matrix.list }}
        run: |
          sing-box rule-set convert --type adguard --output hagezi-${{ matrix.list }}.srs hagezi-${{ matrix.list }}.txt
          echo "Generated rule-set: hagezi-${{ matrix.list }}.srs"
          ls -lh hagezi-${{ matrix.list }}.srs

      - name: Upload to Release - ${{ matrix.list }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create_tag.outputs.tag_name }}
          files: hagezi-${{ matrix.list }}.srs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
